name: Sync Squash Message

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sync_squash_message:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR title and Squash message are the same
        id: check_messages
        run: |
          pr_title="${{ github.event.pull_request.title }}"
          echo "${{github.event}}"
          echo "${{ github.event.head_commit.message }}"
          squash_message=$(git log -n 1 --format=%s ${{ github.event.before }}..${{ github.event.after }})
          echo "$squash_message"
          if [ "$pr_title" != "$squash_message" ]; then
            echo "PR title and Squash message are different. Updating Squash message..."
            git commit --amend -m "$pr_title"
            git push origin HEAD -f
          else
            echo "PR title and Squash message are the same. Nothing to update."
          fi
        env:
          PR_NUMBER: ${{ github.event.number }}
